export { default as HomeLayout } from "./HomeLayout";
export { default as Landing } from "./Landing";
export { default as About } from "./About";
export { default as SingleStory } from "./SingleStory";
export { default as GameLogin } from "./GameLogin";
export { default as GameInstruction } from "./GameInstruction";
export { default as Game } from "./Game";
export { default as Error } from "./Error";
export { default as SingleError } from "./SingleError";
